"""Initial schema

Revision ID: 426d010ea5a1
Revises: 
Create Date: 2026-10-01 08:49:41.690896
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '426d010ea5a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['accounting_category.id'], name=op.f('fk_accounting_category_parent_id_accounting_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_category'))
    )
    with op.batch_alter_table('accounting_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_category_kind'), ['kind'], unique=False)

    op.create_table('app_setting',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('value_type', sa.String(length=20), server_default='string', nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('updated_at', sa.String(length=30), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting'))
    )
    op.create_table('backup_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='started', nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('triggered_by', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('schema_version', sa.String(length=40), server_default='', nullable=False),
    sa.Column('checksum', sa.String(length=128), server_default='', nullable=False),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_record'))
    )
    with op.batch_alter_table('backup_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_record_status'), ['status'], unique=False)

    op.create_table('clinic_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tagline', sa.String(length=255), server_default='', nullable=False),
    sa.Column('logo_path', sa.String(length=500), server_default='', nullable=False),
    sa.Column('address', sa.Text(), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=False),
    sa.Column('email', sa.String(length=200), server_default='', nullable=False),
    sa.Column('website', sa.String(length=200), server_default='', nullable=False),
    sa.Column('prescription_footer', sa.Text(), server_default='', nullable=False),
    sa.Column('currency_code', sa.String(length=8), server_default='BDT', nullable=False),
    sa.Column('setup_completed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinic_profile'))
    )
    op.create_table('clinical_template_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=30), nullable=False),
    sa.Column('display_text', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_template_option'))
    )
    with op.batch_alter_table('clinical_template_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_template_option_section_key'), ['section_key'], unique=False)

    op.create_table('dentist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qualifications', sa.Text(), server_default='', nullable=False),
    sa.Column('certifications', sa.Text(), server_default='', nullable=False),
    sa.Column('registration_no', sa.String(length=100), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=False),
    sa.Column('email', sa.String(length=200), server_default='', nullable=False),
    sa.Column('signature_path', sa.String(length=500), server_default='', nullable=False),
    sa.Column('photo_path', sa.String(length=500), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dentist'))
    )
    op.create_table('designation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designation')),
    sa.UniqueConstraint('name', name=op.f('uq_designation_name'))
    )
    op.create_table('inventory_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['inventory_category.id'], name=op.f('fk_inventory_category_parent_id_inventory_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_category'))
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_method')),
    sa.UniqueConstraint('code', name=op.f('uq_payment_method_code'))
    )
    op.create_table('printer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('paper_size', sa.String(length=40), server_default='A4', nullable=False),
    sa.Column('orientation', sa.String(length=20), server_default='portrait', nullable=False),
    sa.Column('margin_top_mm', sa.Integer(), server_default='10', nullable=False),
    sa.Column('margin_bottom_mm', sa.Integer(), server_default='10', nullable=False),
    sa.Column('margin_left_mm', sa.Integer(), server_default='10', nullable=False),
    sa.Column('margin_right_mm', sa.Integer(), server_default='10', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('target_printer', sa.String(length=200), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_printer_profile')),
    sa.UniqueConstraint('name', name=op.f('uq_printer_profile_name'))
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), server_default='', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role_title', sa.String(length=120), server_default='', nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), server_default='', nullable=False),
    sa.Column('blood_group', sa.String(length=10), server_default='', nullable=False),
    sa.Column('address', sa.Text(), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=False),
    sa.Column('email', sa.String(length=200), server_default='', nullable=False),
    sa.Column('nid', sa.String(length=50), server_default='', nullable=False),
    sa.Column('photo_path', sa.String(length=500), server_default='', nullable=False),
    sa.Column('salary_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff'))
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=False),
    sa.Column('address', sa.Text(), server_default='', nullable=False),
    sa.Column('email', sa.String(length=200), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier'))
    )
    op.create_table('tooth_reference',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('quadrant', sa.Integer(), nullable=False),
    sa.Column('is_pediatric', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notation_ada', sa.String(length=8), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_tooth_reference'))
    )
    op.create_table('treatment_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('category', sa.String(length=100), server_default='', nullable=False),
    sa.Column('default_price_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_catalog')),
    sa.UniqueConstraint('name', name=op.f('uq_treatment_catalog_name'))
    )
    with op.batch_alter_table('treatment_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_catalog_category'), ['category'], unique=False)

    op.create_table('dentist_designations',
    sa.Column('dentist_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentist.id'], name=op.f('fk_dentist_designations_dentist_id_dentist'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['designation_id'], ['designation.id'], name=op.f('fk_dentist_designations_designation_id_designation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dentist_id', 'designation_id', name=op.f('pk_dentist_designations'))
    )
    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=60), server_default='', nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=30), server_default='pcs', nullable=False),
    sa.Column('location', sa.String(length=200), server_default='', nullable=False),
    sa.Column('min_level_qty', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('current_qty', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_category.id'], name=op.f('fk_inventory_item_category_id_inventory_category'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_item'))
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_item_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_item_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_item_sku'), ['sku'], unique=False)

    op.create_table('permission_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_permission_assignment_role_id_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_assignment'))
    )
    with op.batch_alter_table('permission_assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_assignment_role_id'), ['role_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_set_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_user_role_id_role')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_user_staff_id_staff'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attachable_type', sa.String(length=40), nullable=False),
    sa.Column('attachable_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), server_default='', nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('title', sa.String(length=255), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('fk_attachment_uploaded_by_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment'))
    )
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachment_attachable_id'), ['attachable_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachment_attachable_type'), ['attachable_type'], unique=False)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), server_default='', nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('ip_or_machine', sa.String(length=200), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_event_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_event_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_user_id'), ['user_id'], unique=False)

    op.create_table('inventory_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('batch_no', sa.String(length=100), server_default='', nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('reference', sa.String(length=200), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_inventory_movement_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_item.id'], name=op.f('fk_inventory_movement_item_id_inventory_item'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_inventory_movement_supplier_id_supplier'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movement'))
    )
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movement_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_movement_movement_type'), ['movement_type'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), server_default='', nullable=False),
    sa.Column('payload_json', sa.Text(), server_default='', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('age_cache', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), server_default='', nullable=False),
    sa.Column('blood_group', sa.String(length=10), server_default='', nullable=False),
    sa.Column('address', sa.Text(), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=50), server_default='', nullable=False),
    sa.Column('emergency_phone', sa.String(length=50), server_default='', nullable=False),
    sa.Column('email', sa.String(length=200), server_default='', nullable=False),
    sa.Column('chief_complaint', sa.Text(), server_default='', nullable=False),
    sa.Column('medical_history', sa.Text(), server_default='', nullable=False),
    sa.Column('allergies', sa.Text(), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_visit_at', sa.DateTime(), nullable=True),
    sa.Column('visit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_patient_created_by_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient'))
    )
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_patient_code'), ['patient_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_patient_phone'), ['phone'], unique=False)

    op.create_table('appointment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dentist_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('reason', sa.String(length=255), server_default='', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='scheduled', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_appointment_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentist.id'], name=op.f('fk_appointment_dentist_id_dentist'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_appointment_patient_id_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointment'))
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointment_status'), ['status'], unique=False)

    op.create_table('visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dentist_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=255), server_default='', nullable=False),
    sa.Column('chief_complaint', sa.Text(), server_default='', nullable=False),
    sa.Column('on_examination', sa.Text(), server_default='', nullable=False),
    sa.Column('advice', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_visit_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentist.id'], name=op.f('fk_visit_dentist_id_dentist'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_visit_patient_id_patient'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit'))
    )
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visit_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visit_visit_date'), ['visit_date'], unique=False)

    op.create_table('dental_chart_finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('tooth_code', sa.String(length=8), nullable=False),
    sa.Column('finding', sa.String(length=40), nullable=False),
    sa.Column('surface', sa.String(length=20), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_dental_chart_finding_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tooth_code'], ['tooth_reference.code'], name=op.f('fk_dental_chart_finding_tooth_code_tooth_reference'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], name=op.f('fk_dental_chart_finding_visit_id_visit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dental_chart_finding'))
    )
    with op.batch_alter_table('dental_chart_finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dental_chart_finding_finding'), ['finding'], unique=False)
        batch_op.create_index(batch_op.f('ix_dental_chart_finding_tooth_code'), ['tooth_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_dental_chart_finding_visit_id'), ['visit_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dentist_id', sa.Integer(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('subtotal_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tax_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paid_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('due_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='unpaid', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('is_posted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('void_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_invoice_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentist.id'], name=op.f('fk_invoice_dentist_id_dentist'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_invoice_patient_id_patient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], name=op.f('fk_invoice_visit_id_visit'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice'))
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_number'), ['invoice_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoice_is_posted'), ['is_posted'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_visit_id'), ['visit_id'], unique=False)

    op.create_table('prescription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dentist_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('chief_complaint', sa.Text(), server_default='', nullable=False),
    sa.Column('on_examination', sa.Text(), server_default='', nullable=False),
    sa.Column('advice', sa.Text(), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('finalized', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_prescription_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentist.id'], name=op.f('fk_prescription_dentist_id_dentist'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_prescription_patient_id_patient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], name=op.f('fk_prescription_visit_id_visit'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription'))
    )
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_finalized'), ['finalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prescription_visit_id'), ['visit_id'], unique=False)

    op.create_table('queue_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dentist_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='waiting', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('arrived_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], name=op.f('fk_queue_entry_appointment_id_appointment'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_queue_entry_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentist.id'], name=op.f('fk_queue_entry_dentist_id_dentist'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_queue_entry_patient_id_patient'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_entry'))
    )
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entry_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entry_dentist_id'), ['dentist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entry_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entry_status'), ['status'], unique=False)

    op.create_table('treatment_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('dentist_id', sa.Integer(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('name_at_service_time', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('tooth_codes', sa.String(length=255), server_default='', nullable=False),
    sa.Column('price_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['treatment_catalog.id'], name=op.f('fk_treatment_record_catalog_id_treatment_catalog'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_treatment_record_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dentist_id'], ['dentist.id'], name=op.f('fk_treatment_record_dentist_id_dentist'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_treatment_record_patient_id_patient'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['visit_id'], ['visit.id'], name=op.f('fk_treatment_record_visit_id_visit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_record'))
    )
    with op.batch_alter_table('treatment_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treatment_record_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_record_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_treatment_record_visit_id'), ['visit_id'], unique=False)

    op.create_table('invoice_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=30), server_default='custom', nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('discount_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('line_total_paisa', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_invoice_line_item_invoice_id_invoice'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_item'))
    )
    with op.batch_alter_table('invoice_line_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_item_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('amount_paisa', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.String(length=100), server_default='', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('reversal_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_payment_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], name=op.f('fk_payment_invoice_id_invoice'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['method_id'], ['payment_method.id'], name=op.f('fk_payment_method_id_payment_method'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name=op.f('fk_payment_patient_id_patient'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment'))
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_method_id'), ['method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_patient_id'), ['patient_id'], unique=False)

    op.create_table('prescription_medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('form', sa.String(length=50), server_default='', nullable=False),
    sa.Column('strength', sa.String(length=100), server_default='', nullable=False),
    sa.Column('frequency_morning', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('frequency_noon', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('frequency_night', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('meal_relation', sa.String(length=20), server_default='after', nullable=False),
    sa.Column('duration_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('quantity', sa.String(length=50), server_default='', nullable=False),
    sa.Column('instructions', sa.String(length=300), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], name=op.f('fk_prescription_medicine_prescription_id_prescription'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prescription_medicine'))
    )
    with op.batch_alter_table('prescription_medicine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prescription_medicine_prescription_id'), ['prescription_id'], unique=False)

    op.create_table('accounting_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('amount_paisa', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('related_invoice_id', sa.Integer(), nullable=True),
    sa.Column('related_payment_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['accounting_category.id'], name=op.f('fk_accounting_entry_category_id_accounting_category'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_accounting_entry_created_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], name=op.f('fk_accounting_entry_payment_method_id_payment_method'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['invoice.id'], name=op.f('fk_accounting_entry_related_invoice_id_invoice'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_payment_id'], ['payment.id'], name=op.f('fk_accounting_entry_related_payment_id_payment'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounting_entry'))
    )
    with op.batch_alter_table('accounting_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_entry_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_entry_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounting_entry_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_entry_kind'))
        batch_op.drop_index(batch_op.f('ix_accounting_entry_date'))
        batch_op.drop_index(batch_op.f('ix_accounting_entry_category_id'))

    op.drop_table('accounting_entry')
    with op.batch_alter_table('prescription_medicine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_medicine_prescription_id'))

    op.drop_table('prescription_medicine')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_patient_id'))
        batch_op.drop_index(batch_op.f('ix_payment_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_payment_invoice_id'))

    op.drop_table('payment')
    with op.batch_alter_table('invoice_line_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_item_invoice_id'))

    op.drop_table('invoice_line_item')
    with op.batch_alter_table('treatment_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_record_visit_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_record_patient_id'))
        batch_op.drop_index(batch_op.f('ix_treatment_record_catalog_id'))

    op.drop_table('treatment_record')
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entry_status'))
        batch_op.drop_index(batch_op.f('ix_queue_entry_patient_id'))
        batch_op.drop_index(batch_op.f('ix_queue_entry_dentist_id'))
        batch_op.drop_index(batch_op.f('ix_queue_entry_appointment_id'))

    op.drop_table('queue_entry')
    with op.batch_alter_table('prescription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prescription_visit_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_patient_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_finalized'))
        batch_op.drop_index(batch_op.f('ix_prescription_dentist_id'))
        batch_op.drop_index(batch_op.f('ix_prescription_date'))

    op.drop_table('prescription')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_visit_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_status'))
        batch_op.drop_index(batch_op.f('ix_invoice_patient_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_is_posted'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_number'))
        batch_op.drop_index(batch_op.f('ix_invoice_dentist_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_date'))

    op.drop_table('invoice')
    with op.batch_alter_table('dental_chart_finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dental_chart_finding_visit_id'))
        batch_op.drop_index(batch_op.f('ix_dental_chart_finding_tooth_code'))
        batch_op.drop_index(batch_op.f('ix_dental_chart_finding_finding'))

    op.drop_table('dental_chart_finding')
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_visit_date'))
        batch_op.drop_index(batch_op.f('ix_visit_status'))
        batch_op.drop_index(batch_op.f('ix_visit_patient_id'))
        batch_op.drop_index(batch_op.f('ix_visit_dentist_id'))

    op.drop_table('visit')
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_status'))
        batch_op.drop_index(batch_op.f('ix_appointment_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_appointment_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointment_dentist_id'))

    op.drop_table('appointment')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_phone'))
        batch_op.drop_index(batch_op.f('ix_patient_patient_code'))
        batch_op.drop_index(batch_op.f('ix_patient_name'))
        batch_op.drop_index(batch_op.f('ix_patient_gender'))

    op.drop_table('patient')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_kind'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('inventory_movement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movement_movement_type'))
        batch_op.drop_index(batch_op.f('ix_inventory_movement_item_id'))

    op.drop_table('inventory_movement')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_event_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_event_action'))

    op.drop_table('audit_event')
    with op.batch_alter_table('attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachment_attachable_type'))
        batch_op.drop_index(batch_op.f('ix_attachment_attachable_id'))

    op.drop_table('attachment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_staff_id'))
        batch_op.drop_index(batch_op.f('ix_user_role_id'))

    op.drop_table('user')
    with op.batch_alter_table('permission_assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_assignment_role_id'))

    op.drop_table('permission_assignment')
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_item_sku'))
        batch_op.drop_index(batch_op.f('ix_inventory_item_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_item_category_id'))

    op.drop_table('inventory_item')
    op.drop_table('dentist_designations')
    with op.batch_alter_table('treatment_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treatment_catalog_category'))

    op.drop_table('treatment_catalog')
    op.drop_table('tooth_reference')
    op.drop_table('supplier')
    op.drop_table('staff')
    op.drop_table('role')
    op.drop_table('printer_profile')
    op.drop_table('payment_method')
    op.drop_table('inventory_category')
    op.drop_table('designation')
    op.drop_table('dentist')
    with op.batch_alter_table('clinical_template_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_template_option_section_key'))

    op.drop_table('clinical_template_option')
    op.drop_table('clinic_profile')
    with op.batch_alter_table('backup_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_record_status'))

    op.drop_table('backup_record')
    op.drop_table('app_setting')
    with op.batch_alter_table('accounting_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_category_kind'))

    op.drop_table('accounting_category')
    # ### end Alembic commands ###
